apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  labels:
    app: customer
spec:
  replicas: 1
  template:
    metadata:
      name: customer
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: brunosferraz/customer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 3000m
              memory: 256Mi
      restartPolicy: Always

  selector:
    matchLabels:
      app: customer