apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 1
  template:
    metadata:
      name: notification
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: brunosferraz/notification:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 256Mi
      restartPolicy: Always

  selector:
    matchLabels:
      app: notification